"""Add affiliate fields to store

Revision ID: 56bdcc289507
Revises: 1e074146f125
Create Date: 2026-01-14 00:23:33.953697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56bdcc289507'
down_revision: Union[str, Sequence[str], None] = '1e074146f125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('affiliate_network', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('affiliate_program_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'affiliate_program_id')
    op.drop_column('stores', 'affiliate_network')
    # ### end Alembic commands ###
